import mysql.connector
mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    passwd="Shivam@02"

)
mycurs=mydb.cursor()
mycurs.execute("USE ula")


# #Trigger 1
# #Creating a new payment record in the Payment table when the Completion_Status column of a record in the Ride table is updated from "FALSE" to "TRUE".
# mycurs.execute('''
#     CREATE TRIGGER insert_payment
#     AFTER UPDATE ON Ride
#     FOR EACH ROW
#     BEGIN
#         IF (NEW.Completion_Status = 'TRUE' AND OLD.Completion_Status = 'FALSE') THEN
#             INSERT INTO Payment(Payment_id,Customer_id, Driver_id, Vehicle_PLATE, Amount, Paytime, Method)
#             VALUES(NEW.Customer_id,NEW.Customer_id, NEW.Driver_id, NEW.Vehicle_PLATE, 20.00,NEW.RIDE_TIME,'mastercard');
#         END IF;
#     END$$
# ''')
# mydb.commit()

# #Trigger 2
# #Deletion of a driver record from the Driver table if there are pending rides associated with that driver.

# mycursor = mydb.cursor()

# mycursor.execute("""
#     CREATE TRIGGER prevent_driver_deletion
#     BEFORE DELETE ON Driver
#     FOR EACH ROW
#     BEGIN
#         DECLARE num_pending_rides INT;
#         SELECT COUNT(*) INTO num_pending_rides FROM Ride WHERE Driver_id = OLD.Driver_id AND Completion_Status = 'FALSE';
#         IF num_pending_rides > 0 THEN
#             SIGNAL SQLSTATE '45000'
#                 SET MESSAGE_TEXT = 'Cannot delete driver with pending rides';
#         END IF;
#     END;
# """)

# mydb.commit()



while(True):
    print("Select the Query You want to run: ")
    print("A) Embedded Queries")
    print("B) OLAP Queries")
    choice1 = input("Enter your choice: ")

    # Embedded Queries
    if choice == 'A':
        print("1) List all the payments made by a specific customer:")
        print("2) Find the total amount earned by each driver:")
        choice3 = input("Enter your choice: ")
        if choice3 == '1':
            mycurs.execute("SELECT Payment_id, Amount, Paytime, Method FROM Payment WHERE Customer_id = (SELECT Customer_id FROM Customer WHERE First_Name = 'John'); ")
            results = mycurs.fetchall()
            for row in results:
                print(row)
        elif choice3 == '2':
            mycurs.execute("SELECT d.Driver_id, d.First_Name, d.Last_Name, SUM(p.Amount) AS total_earnings FROM Driver d LEFT JOIN Payment p ON d.Driver_id = p.Driver_id GROUP BY d.Driver_id;")
            results = mycurs.fetchall()
            for row in results:
                print(row)
        else:
            print("Invalid choice. Please try again.")

    # OLAP Queries
    elif choice == 'B':
        print("1) Show the total number of rides completed by each driver for each month in the year 2022:")
        print("2) Show the total amount paid by customers using different payment methods and the total amount paid by drivers using different payment methods.")
        print("3) Retrieve the total revenue generated by each vehicle manufacturer, sorted by manufacturer and year:")
        print("4) Find the total revenue earned by each driver and the total revenue earned by all drivers, grouped by driver and vehicle, with a grand total:")
        print("5) EXIT")
        choice = input("Enter your choice: ")
        if choice == '1':
            mycurs.execute("SELECT Driver_id, MONTH(RIDE_DATE) AS Month, COUNT(*) AS Total_Rides FROM Ride WHERE YEAR(RIDE_DATE) = 2022 AND Completion_status = 'TRUE' GROUP BY Driver_id, Month;")
            results = mycurs.fetchall()
            for row in results:
                print(row)
        elif choice == '2':
            mycurs.execute("SELECT Method, Driver_id, SUM(Amount) AS Total_Amount FROM Payment GROUP BY CUBE(Method, Driver_id);")
            results = mycurs.fetchall()
            for row in results:
                print(row)
        elif choice == '3':
            mycurs.execute("SELECT COMPANY, Manu_year, SUM(Amount) AS TotalRevenue FROM Payment P JOIN VEHICLE V ON P.VEHICLE_PLATE = V.VEHICLE_PLATE GROUP BY COMPANY, Manu_year WITH ROLLUP;")
            results = mycurs.fetchall()
            for row in results:
                print(row)
        elif choice == '4':
            mycurs.execute("SELECT Driver.Driver_id, Driver.First_Name, Driver.Last_Name, Vehicle.MODEL, SUM(Payment.Amount) AS Total_Revenue FROM Payment LEFT JOIN Driver ON Payment.Driver_id = Driver.Driver_id LEFT JOIN Vehicle ON Payment.VEHICLE_PLATE = Vehicle.VEHICLE_PLATE GROUP BY Driver.Driver_id, Vehicle.MODEL WITH ROLLUP;")
            results = mycurs.fetchall()
            for row in results:
                print(row)
        elif choice == '5':
            break
        else:
            print("Invalid choice. Please try again.")
    else:
            print("Invalid choice. Please try again.")
